[project]
name = "tla-advisor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "genericmaster", email = "rakhivhanithendo@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.5.9",
    "ollama>=0.6.2",
    "python-dotenv>=1.2.2",
]

[project.scripts]
tla-advisor= "tla_advisor:main"

[build-system]
requires = ["uv_build>=0.10.7,<0.11.0"]
build-backend = "uv_build"
